"""
    Finatic FastAPI Backend

    FinaticAPI REST API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictStr
from typing import Optional
from typing_extensions import Annotated
from finatic_server_legacy.models.create_session_request import CreateSessionRequest
from finatic_server_legacy.models.finatic_broker_factory_core_standard_models_abstract_responses_finatic_response_session_response_data1 import FinaticBrokerFactoryCoreStandardModelsAbstractResponsesFinaticResponseSessionResponseData1
from finatic_server_legacy.models.finatic_broker_factory_core_standard_models_abstract_responses_finatic_response_token_response_data1 import FinaticBrokerFactoryCoreStandardModelsAbstractResponsesFinaticResponseTokenResponseData1
from finatic_server_legacy.models.finatic_environment import FinaticEnvironment
from finatic_server_legacy.models.finatic_response_dict_str_union_str_none_type import FinaticResponseDictStrUnionStrNoneType
from finatic_server_legacy.models.finatic_response_session_sync_status_response import FinaticResponseSessionSyncStatusResponse

from finatic_server_legacy.api_client import ApiClient, RequestSerialized
from finatic_server_legacy.api_response import ApiResponse
from finatic_server_legacy.rest import RESTResponseType


class SessionsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def finatic_v1_get_sessions_session_id(
        self,
        session_id: StrictStr,
        x_api_key: Annotated[StrictStr, Field(description="Company API key")],
        x_finatic_environment: Annotated[Optional[FinaticEnvironment], Field(description="Select the Finatic environment for account-first v1 calls. Defaults to the API-key environment when omitted.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> FinaticBrokerFactoryCoreStandardModelsAbstractResponsesFinaticResponseSessionResponseData1:
        """Get Session

        Get a v1 session by id.

        :param session_id: (required)
        :type session_id: str
        :param x_api_key: Company API key (required)
        :type x_api_key: str
        :param x_finatic_environment: Select the Finatic environment for account-first v1 calls. Defaults to the API-key environment when omitted.
        :type x_finatic_environment: FinaticEnvironment
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._finatic_v1_get_sessions_session_id_serialize(
            session_id=session_id,
            x_api_key=x_api_key,
            x_finatic_environment=x_finatic_environment,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "FinaticBrokerFactoryCoreStandardModelsAbstractResponsesFinaticResponseSessionResponseData1",
            '400': "FinaticAPIErrorResponse",
            '401': "FinaticAPIErrorResponse",
            '403': "FinaticAPIErrorResponse",
            '404': "FinaticAPIErrorResponse",
            '409': "FinaticAPIErrorResponse",
            '422': "FinaticAPIErrorResponse",
            '429': "FinaticAPIErrorResponse",
            '500': "FinaticAPIErrorResponse",
            '502': "FinaticAPIErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def finatic_v1_get_sessions_session_id_with_http_info(
        self,
        session_id: StrictStr,
        x_api_key: Annotated[StrictStr, Field(description="Company API key")],
        x_finatic_environment: Annotated[Optional[FinaticEnvironment], Field(description="Select the Finatic environment for account-first v1 calls. Defaults to the API-key environment when omitted.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[FinaticBrokerFactoryCoreStandardModelsAbstractResponsesFinaticResponseSessionResponseData1]:
        """Get Session

        Get a v1 session by id.

        :param session_id: (required)
        :type session_id: str
        :param x_api_key: Company API key (required)
        :type x_api_key: str
        :param x_finatic_environment: Select the Finatic environment for account-first v1 calls. Defaults to the API-key environment when omitted.
        :type x_finatic_environment: FinaticEnvironment
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._finatic_v1_get_sessions_session_id_serialize(
            session_id=session_id,
            x_api_key=x_api_key,
            x_finatic_environment=x_finatic_environment,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "FinaticBrokerFactoryCoreStandardModelsAbstractResponsesFinaticResponseSessionResponseData1",
            '400': "FinaticAPIErrorResponse",
            '401': "FinaticAPIErrorResponse",
            '403': "FinaticAPIErrorResponse",
            '404': "FinaticAPIErrorResponse",
            '409': "FinaticAPIErrorResponse",
            '422': "FinaticAPIErrorResponse",
            '429': "FinaticAPIErrorResponse",
            '500': "FinaticAPIErrorResponse",
            '502': "FinaticAPIErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def finatic_v1_get_sessions_session_id_without_preload_content(
        self,
        session_id: StrictStr,
        x_api_key: Annotated[StrictStr, Field(description="Company API key")],
        x_finatic_environment: Annotated[Optional[FinaticEnvironment], Field(description="Select the Finatic environment for account-first v1 calls. Defaults to the API-key environment when omitted.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get Session

        Get a v1 session by id.

        :param session_id: (required)
        :type session_id: str
        :param x_api_key: Company API key (required)
        :type x_api_key: str
        :param x_finatic_environment: Select the Finatic environment for account-first v1 calls. Defaults to the API-key environment when omitted.
        :type x_finatic_environment: FinaticEnvironment
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._finatic_v1_get_sessions_session_id_serialize(
            session_id=session_id,
            x_api_key=x_api_key,
            x_finatic_environment=x_finatic_environment,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "FinaticBrokerFactoryCoreStandardModelsAbstractResponsesFinaticResponseSessionResponseData1",
            '400': "FinaticAPIErrorResponse",
            '401': "FinaticAPIErrorResponse",
            '403': "FinaticAPIErrorResponse",
            '404': "FinaticAPIErrorResponse",
            '409': "FinaticAPIErrorResponse",
            '422': "FinaticAPIErrorResponse",
            '429': "FinaticAPIErrorResponse",
            '500': "FinaticAPIErrorResponse",
            '502': "FinaticAPIErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _finatic_v1_get_sessions_session_id_serialize(
        self,
        session_id,
        x_api_key,
        x_finatic_environment,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if session_id is not None:
            _path_params['sessionId'] = session_id
        # process the query parameters
        # process the header parameters
        if x_api_key is not None:
            _header_params['x-api-key'] = x_api_key
        if x_finatic_environment is not None:
            _header_params['X-Finatic-Environment'] = x_finatic_environment
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/api/v1/sessions/{sessionId}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def finatic_v1_get_sessions_session_id_sync_status(
        self,
        session_id: StrictStr,
        x_api_key: Annotated[StrictStr, Field(description="Company API key")],
        x_finatic_environment: Annotated[Optional[FinaticEnvironment], Field(description="Select the Finatic environment for account-first v1 calls. Defaults to the API-key environment when omitted.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> FinaticResponseSessionSyncStatusResponse:
        """Get Session Sync Status

        Poll selected-account sync readiness for a v1 session.

        :param session_id: (required)
        :type session_id: str
        :param x_api_key: Company API key (required)
        :type x_api_key: str
        :param x_finatic_environment: Select the Finatic environment for account-first v1 calls. Defaults to the API-key environment when omitted.
        :type x_finatic_environment: FinaticEnvironment
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._finatic_v1_get_sessions_session_id_sync_status_serialize(
            session_id=session_id,
            x_api_key=x_api_key,
            x_finatic_environment=x_finatic_environment,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "FinaticResponseSessionSyncStatusResponse",
            '400': "FinaticAPIErrorResponse",
            '401': "FinaticAPIErrorResponse",
            '403': "FinaticAPIErrorResponse",
            '404': "FinaticAPIErrorResponse",
            '409': "FinaticAPIErrorResponse",
            '422': "FinaticAPIErrorResponse",
            '429': "FinaticAPIErrorResponse",
            '500': "FinaticAPIErrorResponse",
            '502': "FinaticAPIErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def finatic_v1_get_sessions_session_id_sync_status_with_http_info(
        self,
        session_id: StrictStr,
        x_api_key: Annotated[StrictStr, Field(description="Company API key")],
        x_finatic_environment: Annotated[Optional[FinaticEnvironment], Field(description="Select the Finatic environment for account-first v1 calls. Defaults to the API-key environment when omitted.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[FinaticResponseSessionSyncStatusResponse]:
        """Get Session Sync Status

        Poll selected-account sync readiness for a v1 session.

        :param session_id: (required)
        :type session_id: str
        :param x_api_key: Company API key (required)
        :type x_api_key: str
        :param x_finatic_environment: Select the Finatic environment for account-first v1 calls. Defaults to the API-key environment when omitted.
        :type x_finatic_environment: FinaticEnvironment
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._finatic_v1_get_sessions_session_id_sync_status_serialize(
            session_id=session_id,
            x_api_key=x_api_key,
            x_finatic_environment=x_finatic_environment,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "FinaticResponseSessionSyncStatusResponse",
            '400': "FinaticAPIErrorResponse",
            '401': "FinaticAPIErrorResponse",
            '403': "FinaticAPIErrorResponse",
            '404': "FinaticAPIErrorResponse",
            '409': "FinaticAPIErrorResponse",
            '422': "FinaticAPIErrorResponse",
            '429': "FinaticAPIErrorResponse",
            '500': "FinaticAPIErrorResponse",
            '502': "FinaticAPIErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def finatic_v1_get_sessions_session_id_sync_status_without_preload_content(
        self,
        session_id: StrictStr,
        x_api_key: Annotated[StrictStr, Field(description="Company API key")],
        x_finatic_environment: Annotated[Optional[FinaticEnvironment], Field(description="Select the Finatic environment for account-first v1 calls. Defaults to the API-key environment when omitted.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get Session Sync Status

        Poll selected-account sync readiness for a v1 session.

        :param session_id: (required)
        :type session_id: str
        :param x_api_key: Company API key (required)
        :type x_api_key: str
        :param x_finatic_environment: Select the Finatic environment for account-first v1 calls. Defaults to the API-key environment when omitted.
        :type x_finatic_environment: FinaticEnvironment
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._finatic_v1_get_sessions_session_id_sync_status_serialize(
            session_id=session_id,
            x_api_key=x_api_key,
            x_finatic_environment=x_finatic_environment,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "FinaticResponseSessionSyncStatusResponse",
            '400': "FinaticAPIErrorResponse",
            '401': "FinaticAPIErrorResponse",
            '403': "FinaticAPIErrorResponse",
            '404': "FinaticAPIErrorResponse",
            '409': "FinaticAPIErrorResponse",
            '422': "FinaticAPIErrorResponse",
            '429': "FinaticAPIErrorResponse",
            '500': "FinaticAPIErrorResponse",
            '502': "FinaticAPIErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _finatic_v1_get_sessions_session_id_sync_status_serialize(
        self,
        session_id,
        x_api_key,
        x_finatic_environment,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if session_id is not None:
            _path_params['sessionId'] = session_id
        # process the query parameters
        # process the header parameters
        if x_api_key is not None:
            _header_params['x-api-key'] = x_api_key
        if x_finatic_environment is not None:
            _header_params['X-Finatic-Environment'] = x_finatic_environment
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/api/v1/sessions/{sessionId}/sync-status',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def finatic_v1_get_sessions_session_id_user(
        self,
        session_id: StrictStr,
        x_api_key: Annotated[StrictStr, Field(description="Company API key")],
        x_finatic_environment: Annotated[Optional[FinaticEnvironment], Field(description="Select the Finatic environment for account-first v1 calls. Defaults to the API-key environment when omitted.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> FinaticResponseDictStrUnionStrNoneType:
        """Get Session User

        Compatibility user polling route for plural sessions.

        :param session_id: (required)
        :type session_id: str
        :param x_api_key: Company API key (required)
        :type x_api_key: str
        :param x_finatic_environment: Select the Finatic environment for account-first v1 calls. Defaults to the API-key environment when omitted.
        :type x_finatic_environment: FinaticEnvironment
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._finatic_v1_get_sessions_session_id_user_serialize(
            session_id=session_id,
            x_api_key=x_api_key,
            x_finatic_environment=x_finatic_environment,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "FinaticResponseDictStrUnionStrNoneType",
            '400': "FinaticAPIErrorResponse",
            '401': "FinaticAPIErrorResponse",
            '403': "FinaticAPIErrorResponse",
            '404': "FinaticAPIErrorResponse",
            '409': "FinaticAPIErrorResponse",
            '422': "FinaticAPIErrorResponse",
            '429': "FinaticAPIErrorResponse",
            '500': "FinaticAPIErrorResponse",
            '502': "FinaticAPIErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def finatic_v1_get_sessions_session_id_user_with_http_info(
        self,
        session_id: StrictStr,
        x_api_key: Annotated[StrictStr, Field(description="Company API key")],
        x_finatic_environment: Annotated[Optional[FinaticEnvironment], Field(description="Select the Finatic environment for account-first v1 calls. Defaults to the API-key environment when omitted.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[FinaticResponseDictStrUnionStrNoneType]:
        """Get Session User

        Compatibility user polling route for plural sessions.

        :param session_id: (required)
        :type session_id: str
        :param x_api_key: Company API key (required)
        :type x_api_key: str
        :param x_finatic_environment: Select the Finatic environment for account-first v1 calls. Defaults to the API-key environment when omitted.
        :type x_finatic_environment: FinaticEnvironment
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._finatic_v1_get_sessions_session_id_user_serialize(
            session_id=session_id,
            x_api_key=x_api_key,
            x_finatic_environment=x_finatic_environment,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "FinaticResponseDictStrUnionStrNoneType",
            '400': "FinaticAPIErrorResponse",
            '401': "FinaticAPIErrorResponse",
            '403': "FinaticAPIErrorResponse",
            '404': "FinaticAPIErrorResponse",
            '409': "FinaticAPIErrorResponse",
            '422': "FinaticAPIErrorResponse",
            '429': "FinaticAPIErrorResponse",
            '500': "FinaticAPIErrorResponse",
            '502': "FinaticAPIErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def finatic_v1_get_sessions_session_id_user_without_preload_content(
        self,
        session_id: StrictStr,
        x_api_key: Annotated[StrictStr, Field(description="Company API key")],
        x_finatic_environment: Annotated[Optional[FinaticEnvironment], Field(description="Select the Finatic environment for account-first v1 calls. Defaults to the API-key environment when omitted.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get Session User

        Compatibility user polling route for plural sessions.

        :param session_id: (required)
        :type session_id: str
        :param x_api_key: Company API key (required)
        :type x_api_key: str
        :param x_finatic_environment: Select the Finatic environment for account-first v1 calls. Defaults to the API-key environment when omitted.
        :type x_finatic_environment: FinaticEnvironment
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._finatic_v1_get_sessions_session_id_user_serialize(
            session_id=session_id,
            x_api_key=x_api_key,
            x_finatic_environment=x_finatic_environment,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "FinaticResponseDictStrUnionStrNoneType",
            '400': "FinaticAPIErrorResponse",
            '401': "FinaticAPIErrorResponse",
            '403': "FinaticAPIErrorResponse",
            '404': "FinaticAPIErrorResponse",
            '409': "FinaticAPIErrorResponse",
            '422': "FinaticAPIErrorResponse",
            '429': "FinaticAPIErrorResponse",
            '500': "FinaticAPIErrorResponse",
            '502': "FinaticAPIErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _finatic_v1_get_sessions_session_id_user_serialize(
        self,
        session_id,
        x_api_key,
        x_finatic_environment,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if session_id is not None:
            _path_params['sessionId'] = session_id
        # process the query parameters
        # process the header parameters
        if x_api_key is not None:
            _header_params['x-api-key'] = x_api_key
        if x_finatic_environment is not None:
            _header_params['X-Finatic-Environment'] = x_finatic_environment
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/api/v1/sessions/{sessionId}/user',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def finatic_v1_post_sessions(
        self,
        x_api_key: Annotated[StrictStr, Field(description="Company API key")],
        x_finatic_environment: Annotated[Optional[FinaticEnvironment], Field(description="Select the Finatic environment for account-first v1 calls. Defaults to the API-key environment when omitted.")] = None,
        create_session_request: Optional[CreateSessionRequest] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> FinaticBrokerFactoryCoreStandardModelsAbstractResponsesFinaticResponseSessionResponseData1:
        """Create Session

        Create an account-first v1 session from a company API key.

        :param x_api_key: Company API key (required)
        :type x_api_key: str
        :param x_finatic_environment: Select the Finatic environment for account-first v1 calls. Defaults to the API-key environment when omitted.
        :type x_finatic_environment: FinaticEnvironment
        :param create_session_request:
        :type create_session_request: CreateSessionRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._finatic_v1_post_sessions_serialize(
            x_api_key=x_api_key,
            x_finatic_environment=x_finatic_environment,
            create_session_request=create_session_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "FinaticBrokerFactoryCoreStandardModelsAbstractResponsesFinaticResponseSessionResponseData1",
            '400': "FinaticAPIErrorResponse",
            '401': "FinaticAPIErrorResponse",
            '403': "FinaticAPIErrorResponse",
            '404': "FinaticAPIErrorResponse",
            '409': "FinaticAPIErrorResponse",
            '422': "FinaticAPIErrorResponse",
            '429': "FinaticAPIErrorResponse",
            '500': "FinaticAPIErrorResponse",
            '502': "FinaticAPIErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def finatic_v1_post_sessions_with_http_info(
        self,
        x_api_key: Annotated[StrictStr, Field(description="Company API key")],
        x_finatic_environment: Annotated[Optional[FinaticEnvironment], Field(description="Select the Finatic environment for account-first v1 calls. Defaults to the API-key environment when omitted.")] = None,
        create_session_request: Optional[CreateSessionRequest] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[FinaticBrokerFactoryCoreStandardModelsAbstractResponsesFinaticResponseSessionResponseData1]:
        """Create Session

        Create an account-first v1 session from a company API key.

        :param x_api_key: Company API key (required)
        :type x_api_key: str
        :param x_finatic_environment: Select the Finatic environment for account-first v1 calls. Defaults to the API-key environment when omitted.
        :type x_finatic_environment: FinaticEnvironment
        :param create_session_request:
        :type create_session_request: CreateSessionRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._finatic_v1_post_sessions_serialize(
            x_api_key=x_api_key,
            x_finatic_environment=x_finatic_environment,
            create_session_request=create_session_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "FinaticBrokerFactoryCoreStandardModelsAbstractResponsesFinaticResponseSessionResponseData1",
            '400': "FinaticAPIErrorResponse",
            '401': "FinaticAPIErrorResponse",
            '403': "FinaticAPIErrorResponse",
            '404': "FinaticAPIErrorResponse",
            '409': "FinaticAPIErrorResponse",
            '422': "FinaticAPIErrorResponse",
            '429': "FinaticAPIErrorResponse",
            '500': "FinaticAPIErrorResponse",
            '502': "FinaticAPIErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def finatic_v1_post_sessions_without_preload_content(
        self,
        x_api_key: Annotated[StrictStr, Field(description="Company API key")],
        x_finatic_environment: Annotated[Optional[FinaticEnvironment], Field(description="Select the Finatic environment for account-first v1 calls. Defaults to the API-key environment when omitted.")] = None,
        create_session_request: Optional[CreateSessionRequest] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Create Session

        Create an account-first v1 session from a company API key.

        :param x_api_key: Company API key (required)
        :type x_api_key: str
        :param x_finatic_environment: Select the Finatic environment for account-first v1 calls. Defaults to the API-key environment when omitted.
        :type x_finatic_environment: FinaticEnvironment
        :param create_session_request:
        :type create_session_request: CreateSessionRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._finatic_v1_post_sessions_serialize(
            x_api_key=x_api_key,
            x_finatic_environment=x_finatic_environment,
            create_session_request=create_session_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "FinaticBrokerFactoryCoreStandardModelsAbstractResponsesFinaticResponseSessionResponseData1",
            '400': "FinaticAPIErrorResponse",
            '401': "FinaticAPIErrorResponse",
            '403': "FinaticAPIErrorResponse",
            '404': "FinaticAPIErrorResponse",
            '409': "FinaticAPIErrorResponse",
            '422': "FinaticAPIErrorResponse",
            '429': "FinaticAPIErrorResponse",
            '500': "FinaticAPIErrorResponse",
            '502': "FinaticAPIErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _finatic_v1_post_sessions_serialize(
        self,
        x_api_key,
        x_finatic_environment,
        create_session_request,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        if x_api_key is not None:
            _header_params['x-api-key'] = x_api_key
        if x_finatic_environment is not None:
            _header_params['X-Finatic-Environment'] = x_finatic_environment
        # process the form parameters
        # process the body parameter
        if create_session_request is not None:
            _body_params = create_session_request


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/api/v1/sessions',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def finatic_v1_post_sessions_session_id_portal_links(
        self,
        session_id: StrictStr,
        x_api_key: Annotated[StrictStr, Field(description="Company API key")],
        x_finatic_environment: Annotated[Optional[FinaticEnvironment], Field(description="Select the Finatic environment for account-first v1 calls. Defaults to the API-key environment when omitted.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> FinaticBrokerFactoryCoreStandardModelsAbstractResponsesFinaticResponseTokenResponseData1:
        """Create Portal Link

        Create a one-time portal link token for a v1 session.

        :param session_id: (required)
        :type session_id: str
        :param x_api_key: Company API key (required)
        :type x_api_key: str
        :param x_finatic_environment: Select the Finatic environment for account-first v1 calls. Defaults to the API-key environment when omitted.
        :type x_finatic_environment: FinaticEnvironment
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._finatic_v1_post_sessions_session_id_portal_links_serialize(
            session_id=session_id,
            x_api_key=x_api_key,
            x_finatic_environment=x_finatic_environment,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "FinaticBrokerFactoryCoreStandardModelsAbstractResponsesFinaticResponseTokenResponseData1",
            '400': "FinaticAPIErrorResponse",
            '401': "FinaticAPIErrorResponse",
            '403': "FinaticAPIErrorResponse",
            '404': "FinaticAPIErrorResponse",
            '409': "FinaticAPIErrorResponse",
            '422': "FinaticAPIErrorResponse",
            '429': "FinaticAPIErrorResponse",
            '500': "FinaticAPIErrorResponse",
            '502': "FinaticAPIErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def finatic_v1_post_sessions_session_id_portal_links_with_http_info(
        self,
        session_id: StrictStr,
        x_api_key: Annotated[StrictStr, Field(description="Company API key")],
        x_finatic_environment: Annotated[Optional[FinaticEnvironment], Field(description="Select the Finatic environment for account-first v1 calls. Defaults to the API-key environment when omitted.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[FinaticBrokerFactoryCoreStandardModelsAbstractResponsesFinaticResponseTokenResponseData1]:
        """Create Portal Link

        Create a one-time portal link token for a v1 session.

        :param session_id: (required)
        :type session_id: str
        :param x_api_key: Company API key (required)
        :type x_api_key: str
        :param x_finatic_environment: Select the Finatic environment for account-first v1 calls. Defaults to the API-key environment when omitted.
        :type x_finatic_environment: FinaticEnvironment
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._finatic_v1_post_sessions_session_id_portal_links_serialize(
            session_id=session_id,
            x_api_key=x_api_key,
            x_finatic_environment=x_finatic_environment,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "FinaticBrokerFactoryCoreStandardModelsAbstractResponsesFinaticResponseTokenResponseData1",
            '400': "FinaticAPIErrorResponse",
            '401': "FinaticAPIErrorResponse",
            '403': "FinaticAPIErrorResponse",
            '404': "FinaticAPIErrorResponse",
            '409': "FinaticAPIErrorResponse",
            '422': "FinaticAPIErrorResponse",
            '429': "FinaticAPIErrorResponse",
            '500': "FinaticAPIErrorResponse",
            '502': "FinaticAPIErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def finatic_v1_post_sessions_session_id_portal_links_without_preload_content(
        self,
        session_id: StrictStr,
        x_api_key: Annotated[StrictStr, Field(description="Company API key")],
        x_finatic_environment: Annotated[Optional[FinaticEnvironment], Field(description="Select the Finatic environment for account-first v1 calls. Defaults to the API-key environment when omitted.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Create Portal Link

        Create a one-time portal link token for a v1 session.

        :param session_id: (required)
        :type session_id: str
        :param x_api_key: Company API key (required)
        :type x_api_key: str
        :param x_finatic_environment: Select the Finatic environment for account-first v1 calls. Defaults to the API-key environment when omitted.
        :type x_finatic_environment: FinaticEnvironment
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._finatic_v1_post_sessions_session_id_portal_links_serialize(
            session_id=session_id,
            x_api_key=x_api_key,
            x_finatic_environment=x_finatic_environment,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "FinaticBrokerFactoryCoreStandardModelsAbstractResponsesFinaticResponseTokenResponseData1",
            '400': "FinaticAPIErrorResponse",
            '401': "FinaticAPIErrorResponse",
            '403': "FinaticAPIErrorResponse",
            '404': "FinaticAPIErrorResponse",
            '409': "FinaticAPIErrorResponse",
            '422': "FinaticAPIErrorResponse",
            '429': "FinaticAPIErrorResponse",
            '500': "FinaticAPIErrorResponse",
            '502': "FinaticAPIErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _finatic_v1_post_sessions_session_id_portal_links_serialize(
        self,
        session_id,
        x_api_key,
        x_finatic_environment,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if session_id is not None:
            _path_params['sessionId'] = session_id
        # process the query parameters
        # process the header parameters
        if x_api_key is not None:
            _header_params['x-api-key'] = x_api_key
        if x_finatic_environment is not None:
            _header_params['X-Finatic-Environment'] = x_finatic_environment
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/api/v1/sessions/{sessionId}/portal-links',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )
