# coding: utf-8

"""
    Finatic FastAPI Backend

    FinaticAPI REST API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, Dict, Optional
from finatic_server.models.broker_data_user_broker_connections import BrokerDataUserBrokerConnections
from finatic_server.models.multi_step_auth_response import MultiStepAuthResponse
from finatic_server.models.sandbox_user_broker_connections import SandboxUserBrokerConnections
from typing import Union, Any, List, Set, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal, Self
from pydantic import Field

DATA_ANY_OF_SCHEMAS = ["BrokerDataUserBrokerConnections", "Dict[str, object]", "MultiStepAuthResponse", "SandboxUserBrokerConnections"]

class Data(BaseModel):
    """
    The response data (None when error is present)
    """

    # data type: Dict[str, object]
    anyof_schema_1_validator: Optional[Dict[str, Any]] = None
    # data type: BrokerDataUserBrokerConnections
    anyof_schema_2_validator: Optional[BrokerDataUserBrokerConnections] = None
    # data type: SandboxUserBrokerConnections
    anyof_schema_3_validator: Optional[SandboxUserBrokerConnections] = None
    # data type: MultiStepAuthResponse
    anyof_schema_4_validator: Optional[MultiStepAuthResponse] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[BrokerDataUserBrokerConnections, Dict[str, object], MultiStepAuthResponse, SandboxUserBrokerConnections]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: Set[str] = { "BrokerDataUserBrokerConnections", "Dict[str, object]", "MultiStepAuthResponse", "SandboxUserBrokerConnections" }

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        if v is None:
            return v

        instance = Data.model_construct()
        error_messages = []
        # validate data type: Dict[str, object]
        try:
            instance.anyof_schema_1_validator = v
            return v
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # validate data type: BrokerDataUserBrokerConnections
        if not isinstance(v, BrokerDataUserBrokerConnections):
            error_messages.append(f"Error! Input type `{type(v)}` is not `BrokerDataUserBrokerConnections`")
        else:
            return v

        # validate data type: SandboxUserBrokerConnections
        if not isinstance(v, SandboxUserBrokerConnections):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SandboxUserBrokerConnections`")
        else:
            return v

        # validate data type: MultiStepAuthResponse
        if not isinstance(v, MultiStepAuthResponse):
            error_messages.append(f"Error! Input type `{type(v)}` is not `MultiStepAuthResponse`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in Data with anyOf schemas: BrokerDataUserBrokerConnections, Dict[str, object], MultiStepAuthResponse, SandboxUserBrokerConnections. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        if json_str is None:
            return instance

        error_messages = []
        # deserialize data into Dict[str, object]
        try:
            # validation
            instance.anyof_schema_1_validator = json.loads(json_str)
            # assign value to actual_instance
            instance.actual_instance = instance.anyof_schema_1_validator
            return instance
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[BrokerDataUserBrokerConnections] = None
        try:
            instance.actual_instance = BrokerDataUserBrokerConnections.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_3_validator: Optional[SandboxUserBrokerConnections] = None
        try:
            instance.actual_instance = SandboxUserBrokerConnections.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_4_validator: Optional[MultiStepAuthResponse] = None
        try:
            instance.actual_instance = MultiStepAuthResponse.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into Data with anyOf schemas: BrokerDataUserBrokerConnections, Dict[str, object], MultiStepAuthResponse, SandboxUserBrokerConnections. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], BrokerDataUserBrokerConnections, Dict[str, object], MultiStepAuthResponse, SandboxUserBrokerConnections]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())
