# coding: utf-8

"""
    Finatic FastAPI Backend

    FinaticAPI REST API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class EaConfigurationPayload(BaseModel):
    """
    One-time connector bootstrap payload.
    """ # noqa: E501
    connector_id: UUID
    connector_secret: StrictStr
    ingest_url: StrictStr
    secret_version: Optional[StrictInt] = 1
    signing_scheme_version: StrictInt
    snapshot_required: StrictBool
    timestamp_skew_seconds: StrictInt
    __properties: ClassVar[List[str]] = ["connector_id", "connector_secret", "ingest_url", "secret_version", "signing_scheme_version", "snapshot_required", "timestamp_skew_seconds"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EaConfigurationPayload from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EaConfigurationPayload from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "connector_id": obj.get("connector_id"),
            "connector_secret": obj.get("connector_secret"),
            "ingest_url": obj.get("ingest_url"),
            "secret_version": obj.get("secret_version") if obj.get("secret_version") is not None else 1,
            "signing_scheme_version": obj.get("signing_scheme_version"),
            "snapshot_required": obj.get("snapshot_required"),
            "timestamp_skew_seconds": obj.get("timestamp_skew_seconds")
        })
        return _obj
