# coding: utf-8

"""
    Finatic FastAPI Backend

    FinaticAPI REST API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class FDXAccountGrantUpdate(BaseModel):
    """
    Mutable account-grant fields.
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, alias="_id")
    can_read: Optional[StrictBool] = Field(default=None, alias="canRead")
    can_trade: Optional[StrictBool] = Field(default=None, alias="canTrade")
    data_clusters: Optional[List[StrictStr]] = Field(default=None, alias="dataClusters")
    expires_at: Optional[datetime] = Field(default=None, alias="expiresAt")
    __properties: ClassVar[List[str]] = ["_id", "canRead", "canTrade", "dataClusters", "expiresAt"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FDXAccountGrantUpdate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if can_read (nullable) is None
        # and model_fields_set contains the field
        if self.can_read is None and "can_read" in self.model_fields_set:
            _dict['canRead'] = None

        # set to None if can_trade (nullable) is None
        # and model_fields_set contains the field
        if self.can_trade is None and "can_trade" in self.model_fields_set:
            _dict['canTrade'] = None

        # set to None if data_clusters (nullable) is None
        # and model_fields_set contains the field
        if self.data_clusters is None and "data_clusters" in self.model_fields_set:
            _dict['dataClusters'] = None

        # set to None if expires_at (nullable) is None
        # and model_fields_set contains the field
        if self.expires_at is None and "expires_at" in self.model_fields_set:
            _dict['expiresAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FDXAccountGrantUpdate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "_id": obj.get("_id"),
            "canRead": obj.get("canRead"),
            "canTrade": obj.get("canTrade"),
            "dataClusters": obj.get("dataClusters"),
            "expiresAt": obj.get("expiresAt")
        })
        return _obj
