# coding: utf-8

"""
    Finatic FastAPI Backend

    FinaticAPI REST API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class FDXConsentGrantCreate(BaseModel):
    """
    Company-created FDX consent request.
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, alias="_id")
    data_clusters: Optional[List[StrictStr]] = Field(default=None, alias="dataClusters")
    duration_days: Optional[StrictInt] = Field(default=None, alias="durationDays")
    initiator: Optional[StrictStr] = 'company'
    lookback_days: Optional[StrictInt] = Field(default=None, alias="lookbackDays")
    parties: Optional[Dict[str, Any]] = None
    resources: Optional[List[Dict[str, Any]]] = None
    user_id: StrictStr = Field(alias="userId")
    __properties: ClassVar[List[str]] = ["_id", "dataClusters", "durationDays", "initiator", "lookbackDays", "parties", "resources", "userId"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FDXConsentGrantCreate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if duration_days (nullable) is None
        # and model_fields_set contains the field
        if self.duration_days is None and "duration_days" in self.model_fields_set:
            _dict['durationDays'] = None

        # set to None if lookback_days (nullable) is None
        # and model_fields_set contains the field
        if self.lookback_days is None and "lookback_days" in self.model_fields_set:
            _dict['lookbackDays'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FDXConsentGrantCreate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "_id": obj.get("_id"),
            "dataClusters": obj.get("dataClusters"),
            "durationDays": obj.get("durationDays"),
            "initiator": obj.get("initiator") if obj.get("initiator") is not None else 'company',
            "lookbackDays": obj.get("lookbackDays"),
            "parties": obj.get("parties"),
            "resources": obj.get("resources"),
            "userId": obj.get("userId")
        })
        return _obj
