# coding: utf-8

"""
    Finatic FastAPI Backend

    FinaticAPI REST API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class FinaticV1AccountSyncStatus(str, Enum):
    """
    Public account sync/auth state. reauth_required represents account or connection authorization state, not provider health.
    """

    """
    allowed enum values
    """
    READY = 'ready'
    SYNCING = 'syncing'
    FAILED = 'failed'
    REAUTH_REQUIRED = 'reauth_required'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of FinaticV1AccountSyncStatus from a JSON string"""
        return cls(json.loads(json_str))
