# coding: utf-8

"""
    Finatic FastAPI Backend

    FinaticAPI REST API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class FinaticEnvironment(str, Enum):
    """
    Finatic execution environment. live uses real broker I/O; sandbox uses Finatic synthetic/mock partner data.
    """

    """
    allowed enum values
    """
    LIVE = 'live'
    SANDBOX = 'sandbox'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of FinaticEnvironment from a JSON string"""
        return cls(json.loads(json_str))
