# coding: utf-8

"""
    Finatic FastAPI Backend

    FinaticAPI REST API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MCPBootstrapResponseData(BaseModel):
    """
    Response data for MCP bearer bootstrap.
    """ # noqa: E501
    access_token: StrictStr = Field(description="Short-lived MCP bearer token")
    company_id: StrictStr = Field(description="Company ID associated to API key")
    environment: StrictStr = Field(description="Token environment claim")
    expires_in: StrictInt = Field(description="Bearer token expiration in seconds")
    resource: StrictStr = Field(description="Bound MCP resource URI")
    scope: StrictStr = Field(description="Granted scopes as a space-delimited string")
    session_id: StrictStr = Field(description="Backed API session ID in Redis")
    token_type: Optional[StrictStr] = Field(default='Bearer', description="OAuth token type")
    __properties: ClassVar[List[str]] = ["access_token", "company_id", "environment", "expires_in", "resource", "scope", "session_id", "token_type"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MCPBootstrapResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MCPBootstrapResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "access_token": obj.get("access_token"),
            "company_id": obj.get("company_id"),
            "environment": obj.get("environment"),
            "expires_in": obj.get("expires_in"),
            "resource": obj.get("resource"),
            "scope": obj.get("scope"),
            "session_id": obj.get("session_id"),
            "token_type": obj.get("token_type") if obj.get("token_type") is not None else 'Bearer'
        })
        return _obj
