# coding: utf-8

"""
    Finatic FastAPI Backend

    FinaticAPI REST API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict
from finatic_server.models.accountnumber import Accountnumber
from finatic_server.models.ninja_trader_order_cancel_query_params import NinjaTraderOrderCancelQueryParams
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class NinjaTraderOrderCancelRequest(BaseModel):
    """
    NinjaTrader cancel-order request body.  Attributes ---------- broker : Literal[\"ninja_trader\"]     Discriminator; must be ``\"ninja_trader\"``. account_number : str | int     Broker-provided account number (top-level). Serialized as ``accountNumber``. order : NinjaTraderOrderCancelQueryParamsUnion     NinjaTrader-specific cancel parameters.  Notes ----- Uses ``extra=\"forbid\"`` and ``populate_by_name=True``.
    """ # noqa: E501
    broker: StrictStr
    account_number: Accountnumber = Field(alias="accountNumber")
    order: NinjaTraderOrderCancelQueryParams
    __properties: ClassVar[List[str]] = ["broker", "accountNumber", "order"]

    @field_validator('broker')
    def broker_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['ninja_trader']):
            raise ValueError("must be one of enum values ('ninja_trader')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NinjaTraderOrderCancelRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of account_number
        if self.account_number:
            _dict['accountNumber'] = self.account_number.to_dict()
        # override the default output from pydantic by calling `to_dict()` of order
        if self.order:
            _dict['order'] = self.order.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NinjaTraderOrderCancelRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "broker": obj.get("broker"),
            "accountNumber": Accountnumber.from_dict(obj["accountNumber"]) if obj.get("accountNumber") is not None else None,
            "order": NinjaTraderOrderCancelQueryParams.from_dict(obj["order"]) if obj.get("order") is not None else None
        })
        return _obj


